repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
        files: ^src/
    -   id: end-of-file-fixer
        files: ^src/
    -   id: check-yaml
        files: ^src/
    -   id: check-added-large-files
        files: ^src/

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.7
    hooks:
    -   id: ruff-check
        args: [--fix, --exit-non-zero-on-fix, "--ignore=UP007,UP042,UP045,E501"]
        files: ^src/
    -   id: ruff-format
        files: ^src/

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v2.3.1
    hooks:
    -   id: mypy
        additional_dependencies: [pydantic]
        args: [--ignore-missing-imports]
        files: ^src/
