"""
ChEMBL example: search and concept details.

ChEMBL bioactive molecules, drugs and targets.

Requirements: the [chembl] extra.

Run from the repository root:

    python docs/examples/core/chembl/chembl_example.py

Generated by docs/examples/scripts/generate_all_examples.py; edit the generator, not this file.
"""

import asyncio
import logging
import textwrap

from knowledge_lookup import KnowledgeSource, create_knowledge_lookup

SOURCE = KnowledgeSource.CHEMBL
QUERY = "aspirin"
CONCEPT_ID = "CHEMBL25"


async def main() -> None:
    lookup = create_knowledge_lookup(enabled_sources=[SOURCE])
    try:
        # The factory always returns a lookup object. An adapter that lacks its API
        # key or optional extra is simply not registered in lookup.adapters.
        if SOURCE not in lookup.adapters:
            print(f"SKIPPED: the {SOURCE.value} adapter is not available.")
            print("It needs the [chembl] extra.")
            print("\nSummary: skipped")
            return
        print(f"The {SOURCE.value} adapter is available.")

        print(f"\nSearching {SOURCE.value} for {QUERY!r} ...")
        result = await lookup.search_concepts(QUERY, sources=[SOURCE], max_results=5)
        print(f"Found {result.total_found} concept(s) in {result.execution_time:.1f}s")
        for source, message in result.errors.items():
            print(f"  Error from {source}: {message}")
        for number, concept in enumerate(result.concepts, start=1):
            print(f"\n  {number}. {concept.primary_label}")
            print(f"     ID:         {concept.primary_id}")
            print(f"     Type:       {concept.concept_type}")
            print(f"     Confidence: {concept.confidence_score}")
            for definition in concept.definitions[:1]:
                print(f"     Definition: {textwrap.shorten(definition, 100)}")
            for mapping in concept.mappings[:3]:
                target = mapping.to_concept
                print(f"     Mapping:    {target.identifier} ({target.source})")
        if not result.concepts:
            print("  No results. The service may be down or its API may have changed.")

        print(f"\nFetching details for {CONCEPT_ID!r} ...")
        details = await lookup.get_concept_details(CONCEPT_ID, source=SOURCE)
        if details is None:
            print("  Not found, or the service did not answer.")
        else:
            print(f"  Label:      {details.primary_label}")
            print(f"  ID:         {details.primary_id}")
            print(f"  Type:       {details.concept_type}")
            if details.synonyms:
                print(f"  Synonyms:   {', '.join(map(str, details.synonyms[:5]))}")
            for definition in details.definitions[:1]:
                print(f"  Definition: {textwrap.shorten(definition, 200)}")
            for identifier in details.identifiers[:3]:
                print(f"  Identifier: {identifier.identifier} ({identifier.source})")

        found = "found" if details else "not found"
        print(f"\nSummary: search={result.total_found} details={found}")
    finally:
        await lookup.close()


if __name__ == "__main__":
    logging.basicConfig(level=logging.ERROR, format="%(levelname)s %(name)s: %(message)s")
    try:
        asyncio.run(main())
    except Exception as exc:  # show a readable message instead of a traceback
        raise SystemExit(f"ERROR: {type(exc).__name__}: {exc}") from None
